
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-system
spec:
  selector:
    matchLabels:
      app: solar-system
  template:
    metadata:
      labels:
        app: solar-system
    spec:
      containers:
      - name: solar-system
        image: siddharth67/solar-system:v6
        ports:
        - containerPort: 80



